application: test-eaglet
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /lib
  static_dir: lib

- url: /javascripts
  static_dir: javascripts

- url: /stylesheets
  static_dir: stylesheets
  
- url: .*
  script: index.py
